// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera_definitions.proto

#ifndef PROTOBUF_INCLUDED_camera_5fdefinitions_2eproto
#define PROTOBUF_INCLUDED_camera_5fdefinitions_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_camera_5fdefinitions_2eproto 

namespace protobuf_camera_5fdefinitions_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_camera_5fdefinitions_2eproto
namespace mvcam {
class AdapterInfo;
class AdapterInfoDefaultTypeInternal;
extern AdapterInfoDefaultTypeInternal _AdapterInfo_default_instance_;
class Configuration;
class ConfigurationDefaultTypeInternal;
extern ConfigurationDefaultTypeInternal _Configuration_default_instance_;
class DeviceInfo;
class DeviceInfoDefaultTypeInternal;
extern DeviceInfoDefaultTypeInternal _DeviceInfo_default_instance_;
class Frame;
class FrameDefaultTypeInternal;
extern FrameDefaultTypeInternal _Frame_default_instance_;
class Parameter;
class ParameterDefaultTypeInternal;
extern ParameterDefaultTypeInternal _Parameter_default_instance_;
class Status;
class StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
}  // namespace mvcam
namespace google {
namespace protobuf {
template<> ::mvcam::AdapterInfo* Arena::CreateMaybeMessage<::mvcam::AdapterInfo>(Arena*);
template<> ::mvcam::Configuration* Arena::CreateMaybeMessage<::mvcam::Configuration>(Arena*);
template<> ::mvcam::DeviceInfo* Arena::CreateMaybeMessage<::mvcam::DeviceInfo>(Arena*);
template<> ::mvcam::Frame* Arena::CreateMaybeMessage<::mvcam::Frame>(Arena*);
template<> ::mvcam::Parameter* Arena::CreateMaybeMessage<::mvcam::Parameter>(Arena*);
template<> ::mvcam::Status* Arena::CreateMaybeMessage<::mvcam::Status>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace mvcam {

enum DeviceControlAction {
  Suspend = 0,
  Resume = 1,
  DeviceControlAction_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DeviceControlAction_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DeviceControlAction_IsValid(int value);
const DeviceControlAction DeviceControlAction_MIN = Suspend;
const DeviceControlAction DeviceControlAction_MAX = Resume;
const int DeviceControlAction_ARRAYSIZE = DeviceControlAction_MAX + 1;

const ::google::protobuf::EnumDescriptor* DeviceControlAction_descriptor();
inline const ::std::string& DeviceControlAction_Name(DeviceControlAction value) {
  return ::google::protobuf::internal::NameOfEnum(
    DeviceControlAction_descriptor(), value);
}
inline bool DeviceControlAction_Parse(
    const ::std::string& name, DeviceControlAction* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DeviceControlAction>(
    DeviceControlAction_descriptor(), name, value);
}
// ===================================================================

class AdapterInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mvcam.AdapterInfo) */ {
 public:
  AdapterInfo();
  virtual ~AdapterInfo();

  AdapterInfo(const AdapterInfo& from);

  inline AdapterInfo& operator=(const AdapterInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AdapterInfo(AdapterInfo&& from) noexcept
    : AdapterInfo() {
    *this = ::std::move(from);
  }

  inline AdapterInfo& operator=(AdapterInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AdapterInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AdapterInfo* internal_default_instance() {
    return reinterpret_cast<const AdapterInfo*>(
               &_AdapterInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AdapterInfo* other);
  friend void swap(AdapterInfo& a, AdapterInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AdapterInfo* New() const final {
    return CreateMaybeMessage<AdapterInfo>(NULL);
  }

  AdapterInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AdapterInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AdapterInfo& from);
  void MergeFrom(const AdapterInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AdapterInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string version = 2;
  void clear_version();
  static const int kVersionFieldNumber = 2;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  #if LANG_CXX11
  void set_version(::std::string&& value);
  #endif
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // string description = 3;
  void clear_description();
  static const int kDescriptionFieldNumber = 3;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // bool in_use = 4;
  void clear_in_use();
  static const int kInUseFieldNumber = 4;
  bool in_use() const;
  void set_in_use(bool value);

  // @@protoc_insertion_point(class_scope:mvcam.AdapterInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  bool in_use_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_camera_5fdefinitions_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Parameter : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mvcam.Parameter) */ {
 public:
  Parameter();
  virtual ~Parameter();

  Parameter(const Parameter& from);

  inline Parameter& operator=(const Parameter& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Parameter(Parameter&& from) noexcept
    : Parameter() {
    *this = ::std::move(from);
  }

  inline Parameter& operator=(Parameter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Parameter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Parameter* internal_default_instance() {
    return reinterpret_cast<const Parameter*>(
               &_Parameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Parameter* other);
  friend void swap(Parameter& a, Parameter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Parameter* New() const final {
    return CreateMaybeMessage<Parameter>(NULL);
  }

  Parameter* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Parameter>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Parameter& from);
  void MergeFrom(const Parameter& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Parameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  double value() const;
  void set_value(double value);

  // double min = 3;
  void clear_min();
  static const int kMinFieldNumber = 3;
  double min() const;
  void set_min(double value);

  // double max = 4;
  void clear_max();
  static const int kMaxFieldNumber = 4;
  double max() const;
  void set_max(double value);

  // @@protoc_insertion_point(class_scope:mvcam.Parameter)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double value_;
  double min_;
  double max_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_camera_5fdefinitions_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Configuration : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mvcam.Configuration) */ {
 public:
  Configuration();
  virtual ~Configuration();

  Configuration(const Configuration& from);

  inline Configuration& operator=(const Configuration& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Configuration(Configuration&& from) noexcept
    : Configuration() {
    *this = ::std::move(from);
  }

  inline Configuration& operator=(Configuration&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Configuration& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Configuration* internal_default_instance() {
    return reinterpret_cast<const Configuration*>(
               &_Configuration_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Configuration* other);
  friend void swap(Configuration& a, Configuration& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Configuration* New() const final {
    return CreateMaybeMessage<Configuration>(NULL);
  }

  Configuration* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Configuration>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Configuration& from);
  void MergeFrom(const Configuration& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Configuration* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .mvcam.Parameter exposure = 1;
  bool has_exposure() const;
  void clear_exposure();
  static const int kExposureFieldNumber = 1;
  private:
  const ::mvcam::Parameter& _internal_exposure() const;
  public:
  const ::mvcam::Parameter& exposure() const;
  ::mvcam::Parameter* release_exposure();
  ::mvcam::Parameter* mutable_exposure();
  void set_allocated_exposure(::mvcam::Parameter* exposure);

  // .mvcam.Parameter frame_rate = 2;
  bool has_frame_rate() const;
  void clear_frame_rate();
  static const int kFrameRateFieldNumber = 2;
  private:
  const ::mvcam::Parameter& _internal_frame_rate() const;
  public:
  const ::mvcam::Parameter& frame_rate() const;
  ::mvcam::Parameter* release_frame_rate();
  ::mvcam::Parameter* mutable_frame_rate();
  void set_allocated_frame_rate(::mvcam::Parameter* frame_rate);

  // .mvcam.Parameter gain = 3;
  bool has_gain() const;
  void clear_gain();
  static const int kGainFieldNumber = 3;
  private:
  const ::mvcam::Parameter& _internal_gain() const;
  public:
  const ::mvcam::Parameter& gain() const;
  ::mvcam::Parameter* release_gain();
  ::mvcam::Parameter* mutable_gain();
  void set_allocated_gain(::mvcam::Parameter* gain);

  // .mvcam.Parameter black_level = 4;
  bool has_black_level() const;
  void clear_black_level();
  static const int kBlackLevelFieldNumber = 4;
  private:
  const ::mvcam::Parameter& _internal_black_level() const;
  public:
  const ::mvcam::Parameter& black_level() const;
  ::mvcam::Parameter* release_black_level();
  ::mvcam::Parameter* mutable_black_level();
  void set_allocated_black_level(::mvcam::Parameter* black_level);

  // .mvcam.Parameter gamma = 5;
  bool has_gamma() const;
  void clear_gamma();
  static const int kGammaFieldNumber = 5;
  private:
  const ::mvcam::Parameter& _internal_gamma() const;
  public:
  const ::mvcam::Parameter& gamma() const;
  ::mvcam::Parameter* release_gamma();
  ::mvcam::Parameter* mutable_gamma();
  void set_allocated_gamma(::mvcam::Parameter* gamma);

  // @@protoc_insertion_point(class_scope:mvcam.Configuration)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::mvcam::Parameter* exposure_;
  ::mvcam::Parameter* frame_rate_;
  ::mvcam::Parameter* gain_;
  ::mvcam::Parameter* black_level_;
  ::mvcam::Parameter* gamma_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_camera_5fdefinitions_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Frame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mvcam.Frame) */ {
 public:
  Frame();
  virtual ~Frame();

  Frame(const Frame& from);

  inline Frame& operator=(const Frame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Frame(Frame&& from) noexcept
    : Frame() {
    *this = ::std::move(from);
  }

  inline Frame& operator=(Frame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Frame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Frame* internal_default_instance() {
    return reinterpret_cast<const Frame*>(
               &_Frame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Frame* other);
  friend void swap(Frame& a, Frame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Frame* New() const final {
    return CreateMaybeMessage<Frame>(NULL);
  }

  Frame* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Frame>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Frame& from);
  void MergeFrom(const Frame& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Frame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 7;
  void clear_data();
  static const int kDataFieldNumber = 7;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  public:
  const ::google::protobuf::Timestamp& timestamp() const;
  ::google::protobuf::Timestamp* release_timestamp();
  ::google::protobuf::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* timestamp);

  // uint64 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // uint32 size = 3;
  void clear_size();
  static const int kSizeFieldNumber = 3;
  ::google::protobuf::uint32 size() const;
  void set_size(::google::protobuf::uint32 value);

  // uint32 height = 4;
  void clear_height();
  static const int kHeightFieldNumber = 4;
  ::google::protobuf::uint32 height() const;
  void set_height(::google::protobuf::uint32 value);

  // uint32 width = 5;
  void clear_width();
  static const int kWidthFieldNumber = 5;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // uint32 pixel_format = 6;
  void clear_pixel_format();
  static const int kPixelFormatFieldNumber = 6;
  ::google::protobuf::uint32 pixel_format() const;
  void set_pixel_format(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mvcam.Frame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::Timestamp* timestamp_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint32 size_;
  ::google::protobuf::uint32 height_;
  ::google::protobuf::uint32 width_;
  ::google::protobuf::uint32 pixel_format_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_camera_5fdefinitions_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mvcam.DeviceInfo) */ {
 public:
  DeviceInfo();
  virtual ~DeviceInfo();

  DeviceInfo(const DeviceInfo& from);

  inline DeviceInfo& operator=(const DeviceInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceInfo(DeviceInfo&& from) noexcept
    : DeviceInfo() {
    *this = ::std::move(from);
  }

  inline DeviceInfo& operator=(DeviceInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceInfo* internal_default_instance() {
    return reinterpret_cast<const DeviceInfo*>(
               &_DeviceInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(DeviceInfo* other);
  friend void swap(DeviceInfo& a, DeviceInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceInfo* New() const final {
    return CreateMaybeMessage<DeviceInfo>(NULL);
  }

  DeviceInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceInfo& from);
  void MergeFrom(const DeviceInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string manufacture = 2;
  void clear_manufacture();
  static const int kManufactureFieldNumber = 2;
  const ::std::string& manufacture() const;
  void set_manufacture(const ::std::string& value);
  #if LANG_CXX11
  void set_manufacture(::std::string&& value);
  #endif
  void set_manufacture(const char* value);
  void set_manufacture(const char* value, size_t size);
  ::std::string* mutable_manufacture();
  ::std::string* release_manufacture();
  void set_allocated_manufacture(::std::string* manufacture);

  // string id = 3;
  void clear_id();
  static const int kIdFieldNumber = 3;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string model = 4;
  void clear_model();
  static const int kModelFieldNumber = 4;
  const ::std::string& model() const;
  void set_model(const ::std::string& value);
  #if LANG_CXX11
  void set_model(::std::string&& value);
  #endif
  void set_model(const char* value);
  void set_model(const char* value, size_t size);
  ::std::string* mutable_model();
  ::std::string* release_model();
  void set_allocated_model(::std::string* model);

  // string version = 5;
  void clear_version();
  static const int kVersionFieldNumber = 5;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  #if LANG_CXX11
  void set_version(::std::string&& value);
  #endif
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // string serial = 6;
  void clear_serial();
  static const int kSerialFieldNumber = 6;
  const ::std::string& serial() const;
  void set_serial(const ::std::string& value);
  #if LANG_CXX11
  void set_serial(::std::string&& value);
  #endif
  void set_serial(const char* value);
  void set_serial(const char* value, size_t size);
  ::std::string* mutable_serial();
  ::std::string* release_serial();
  void set_allocated_serial(::std::string* serial);

  // @@protoc_insertion_point(class_scope:mvcam.DeviceInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr manufacture_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr model_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::internal::ArenaStringPtr serial_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_camera_5fdefinitions_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Status : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mvcam.Status) */ {
 public:
  Status();
  virtual ~Status();

  Status(const Status& from);

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Status(Status&& from) noexcept
    : Status() {
    *this = ::std::move(from);
  }

  inline Status& operator=(Status&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Status& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Status* internal_default_instance() {
    return reinterpret_cast<const Status*>(
               &_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Status* other);
  friend void swap(Status& a, Status& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Status* New() const final {
    return CreateMaybeMessage<Status>(NULL);
  }

  Status* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Status>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Status& from);
  void MergeFrom(const Status& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Status* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double temperature = 1;
  void clear_temperature();
  static const int kTemperatureFieldNumber = 1;
  double temperature() const;
  void set_temperature(double value);

  // @@protoc_insertion_point(class_scope:mvcam.Status)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double temperature_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_camera_5fdefinitions_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AdapterInfo

// string name = 1;
inline void AdapterInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AdapterInfo::name() const {
  // @@protoc_insertion_point(field_get:mvcam.AdapterInfo.name)
  return name_.GetNoArena();
}
inline void AdapterInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mvcam.AdapterInfo.name)
}
#if LANG_CXX11
inline void AdapterInfo::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvcam.AdapterInfo.name)
}
#endif
inline void AdapterInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvcam.AdapterInfo.name)
}
inline void AdapterInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvcam.AdapterInfo.name)
}
inline ::std::string* AdapterInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mvcam.AdapterInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AdapterInfo::release_name() {
  // @@protoc_insertion_point(field_release:mvcam.AdapterInfo.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AdapterInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mvcam.AdapterInfo.name)
}

// string version = 2;
inline void AdapterInfo::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AdapterInfo::version() const {
  // @@protoc_insertion_point(field_get:mvcam.AdapterInfo.version)
  return version_.GetNoArena();
}
inline void AdapterInfo::set_version(const ::std::string& value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mvcam.AdapterInfo.version)
}
#if LANG_CXX11
inline void AdapterInfo::set_version(::std::string&& value) {
  
  version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvcam.AdapterInfo.version)
}
#endif
inline void AdapterInfo::set_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvcam.AdapterInfo.version)
}
inline void AdapterInfo::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvcam.AdapterInfo.version)
}
inline ::std::string* AdapterInfo::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:mvcam.AdapterInfo.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AdapterInfo::release_version() {
  // @@protoc_insertion_point(field_release:mvcam.AdapterInfo.version)
  
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AdapterInfo::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:mvcam.AdapterInfo.version)
}

// string description = 3;
inline void AdapterInfo::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AdapterInfo::description() const {
  // @@protoc_insertion_point(field_get:mvcam.AdapterInfo.description)
  return description_.GetNoArena();
}
inline void AdapterInfo::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mvcam.AdapterInfo.description)
}
#if LANG_CXX11
inline void AdapterInfo::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvcam.AdapterInfo.description)
}
#endif
inline void AdapterInfo::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvcam.AdapterInfo.description)
}
inline void AdapterInfo::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvcam.AdapterInfo.description)
}
inline ::std::string* AdapterInfo::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:mvcam.AdapterInfo.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AdapterInfo::release_description() {
  // @@protoc_insertion_point(field_release:mvcam.AdapterInfo.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AdapterInfo::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:mvcam.AdapterInfo.description)
}

// bool in_use = 4;
inline void AdapterInfo::clear_in_use() {
  in_use_ = false;
}
inline bool AdapterInfo::in_use() const {
  // @@protoc_insertion_point(field_get:mvcam.AdapterInfo.in_use)
  return in_use_;
}
inline void AdapterInfo::set_in_use(bool value) {
  
  in_use_ = value;
  // @@protoc_insertion_point(field_set:mvcam.AdapterInfo.in_use)
}

// -------------------------------------------------------------------

// Parameter

// double value = 2;
inline void Parameter::clear_value() {
  value_ = 0;
}
inline double Parameter::value() const {
  // @@protoc_insertion_point(field_get:mvcam.Parameter.value)
  return value_;
}
inline void Parameter::set_value(double value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:mvcam.Parameter.value)
}

// double min = 3;
inline void Parameter::clear_min() {
  min_ = 0;
}
inline double Parameter::min() const {
  // @@protoc_insertion_point(field_get:mvcam.Parameter.min)
  return min_;
}
inline void Parameter::set_min(double value) {
  
  min_ = value;
  // @@protoc_insertion_point(field_set:mvcam.Parameter.min)
}

// double max = 4;
inline void Parameter::clear_max() {
  max_ = 0;
}
inline double Parameter::max() const {
  // @@protoc_insertion_point(field_get:mvcam.Parameter.max)
  return max_;
}
inline void Parameter::set_max(double value) {
  
  max_ = value;
  // @@protoc_insertion_point(field_set:mvcam.Parameter.max)
}

// -------------------------------------------------------------------

// Configuration

// .mvcam.Parameter exposure = 1;
inline bool Configuration::has_exposure() const {
  return this != internal_default_instance() && exposure_ != NULL;
}
inline void Configuration::clear_exposure() {
  if (GetArenaNoVirtual() == NULL && exposure_ != NULL) {
    delete exposure_;
  }
  exposure_ = NULL;
}
inline const ::mvcam::Parameter& Configuration::_internal_exposure() const {
  return *exposure_;
}
inline const ::mvcam::Parameter& Configuration::exposure() const {
  const ::mvcam::Parameter* p = exposure_;
  // @@protoc_insertion_point(field_get:mvcam.Configuration.exposure)
  return p != NULL ? *p : *reinterpret_cast<const ::mvcam::Parameter*>(
      &::mvcam::_Parameter_default_instance_);
}
inline ::mvcam::Parameter* Configuration::release_exposure() {
  // @@protoc_insertion_point(field_release:mvcam.Configuration.exposure)
  
  ::mvcam::Parameter* temp = exposure_;
  exposure_ = NULL;
  return temp;
}
inline ::mvcam::Parameter* Configuration::mutable_exposure() {
  
  if (exposure_ == NULL) {
    auto* p = CreateMaybeMessage<::mvcam::Parameter>(GetArenaNoVirtual());
    exposure_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mvcam.Configuration.exposure)
  return exposure_;
}
inline void Configuration::set_allocated_exposure(::mvcam::Parameter* exposure) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete exposure_;
  }
  if (exposure) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      exposure = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, exposure, submessage_arena);
    }
    
  } else {
    
  }
  exposure_ = exposure;
  // @@protoc_insertion_point(field_set_allocated:mvcam.Configuration.exposure)
}

// .mvcam.Parameter frame_rate = 2;
inline bool Configuration::has_frame_rate() const {
  return this != internal_default_instance() && frame_rate_ != NULL;
}
inline void Configuration::clear_frame_rate() {
  if (GetArenaNoVirtual() == NULL && frame_rate_ != NULL) {
    delete frame_rate_;
  }
  frame_rate_ = NULL;
}
inline const ::mvcam::Parameter& Configuration::_internal_frame_rate() const {
  return *frame_rate_;
}
inline const ::mvcam::Parameter& Configuration::frame_rate() const {
  const ::mvcam::Parameter* p = frame_rate_;
  // @@protoc_insertion_point(field_get:mvcam.Configuration.frame_rate)
  return p != NULL ? *p : *reinterpret_cast<const ::mvcam::Parameter*>(
      &::mvcam::_Parameter_default_instance_);
}
inline ::mvcam::Parameter* Configuration::release_frame_rate() {
  // @@protoc_insertion_point(field_release:mvcam.Configuration.frame_rate)
  
  ::mvcam::Parameter* temp = frame_rate_;
  frame_rate_ = NULL;
  return temp;
}
inline ::mvcam::Parameter* Configuration::mutable_frame_rate() {
  
  if (frame_rate_ == NULL) {
    auto* p = CreateMaybeMessage<::mvcam::Parameter>(GetArenaNoVirtual());
    frame_rate_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mvcam.Configuration.frame_rate)
  return frame_rate_;
}
inline void Configuration::set_allocated_frame_rate(::mvcam::Parameter* frame_rate) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete frame_rate_;
  }
  if (frame_rate) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      frame_rate = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, frame_rate, submessage_arena);
    }
    
  } else {
    
  }
  frame_rate_ = frame_rate;
  // @@protoc_insertion_point(field_set_allocated:mvcam.Configuration.frame_rate)
}

// .mvcam.Parameter gain = 3;
inline bool Configuration::has_gain() const {
  return this != internal_default_instance() && gain_ != NULL;
}
inline void Configuration::clear_gain() {
  if (GetArenaNoVirtual() == NULL && gain_ != NULL) {
    delete gain_;
  }
  gain_ = NULL;
}
inline const ::mvcam::Parameter& Configuration::_internal_gain() const {
  return *gain_;
}
inline const ::mvcam::Parameter& Configuration::gain() const {
  const ::mvcam::Parameter* p = gain_;
  // @@protoc_insertion_point(field_get:mvcam.Configuration.gain)
  return p != NULL ? *p : *reinterpret_cast<const ::mvcam::Parameter*>(
      &::mvcam::_Parameter_default_instance_);
}
inline ::mvcam::Parameter* Configuration::release_gain() {
  // @@protoc_insertion_point(field_release:mvcam.Configuration.gain)
  
  ::mvcam::Parameter* temp = gain_;
  gain_ = NULL;
  return temp;
}
inline ::mvcam::Parameter* Configuration::mutable_gain() {
  
  if (gain_ == NULL) {
    auto* p = CreateMaybeMessage<::mvcam::Parameter>(GetArenaNoVirtual());
    gain_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mvcam.Configuration.gain)
  return gain_;
}
inline void Configuration::set_allocated_gain(::mvcam::Parameter* gain) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete gain_;
  }
  if (gain) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      gain = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, gain, submessage_arena);
    }
    
  } else {
    
  }
  gain_ = gain;
  // @@protoc_insertion_point(field_set_allocated:mvcam.Configuration.gain)
}

// .mvcam.Parameter black_level = 4;
inline bool Configuration::has_black_level() const {
  return this != internal_default_instance() && black_level_ != NULL;
}
inline void Configuration::clear_black_level() {
  if (GetArenaNoVirtual() == NULL && black_level_ != NULL) {
    delete black_level_;
  }
  black_level_ = NULL;
}
inline const ::mvcam::Parameter& Configuration::_internal_black_level() const {
  return *black_level_;
}
inline const ::mvcam::Parameter& Configuration::black_level() const {
  const ::mvcam::Parameter* p = black_level_;
  // @@protoc_insertion_point(field_get:mvcam.Configuration.black_level)
  return p != NULL ? *p : *reinterpret_cast<const ::mvcam::Parameter*>(
      &::mvcam::_Parameter_default_instance_);
}
inline ::mvcam::Parameter* Configuration::release_black_level() {
  // @@protoc_insertion_point(field_release:mvcam.Configuration.black_level)
  
  ::mvcam::Parameter* temp = black_level_;
  black_level_ = NULL;
  return temp;
}
inline ::mvcam::Parameter* Configuration::mutable_black_level() {
  
  if (black_level_ == NULL) {
    auto* p = CreateMaybeMessage<::mvcam::Parameter>(GetArenaNoVirtual());
    black_level_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mvcam.Configuration.black_level)
  return black_level_;
}
inline void Configuration::set_allocated_black_level(::mvcam::Parameter* black_level) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete black_level_;
  }
  if (black_level) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      black_level = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, black_level, submessage_arena);
    }
    
  } else {
    
  }
  black_level_ = black_level;
  // @@protoc_insertion_point(field_set_allocated:mvcam.Configuration.black_level)
}

// .mvcam.Parameter gamma = 5;
inline bool Configuration::has_gamma() const {
  return this != internal_default_instance() && gamma_ != NULL;
}
inline void Configuration::clear_gamma() {
  if (GetArenaNoVirtual() == NULL && gamma_ != NULL) {
    delete gamma_;
  }
  gamma_ = NULL;
}
inline const ::mvcam::Parameter& Configuration::_internal_gamma() const {
  return *gamma_;
}
inline const ::mvcam::Parameter& Configuration::gamma() const {
  const ::mvcam::Parameter* p = gamma_;
  // @@protoc_insertion_point(field_get:mvcam.Configuration.gamma)
  return p != NULL ? *p : *reinterpret_cast<const ::mvcam::Parameter*>(
      &::mvcam::_Parameter_default_instance_);
}
inline ::mvcam::Parameter* Configuration::release_gamma() {
  // @@protoc_insertion_point(field_release:mvcam.Configuration.gamma)
  
  ::mvcam::Parameter* temp = gamma_;
  gamma_ = NULL;
  return temp;
}
inline ::mvcam::Parameter* Configuration::mutable_gamma() {
  
  if (gamma_ == NULL) {
    auto* p = CreateMaybeMessage<::mvcam::Parameter>(GetArenaNoVirtual());
    gamma_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mvcam.Configuration.gamma)
  return gamma_;
}
inline void Configuration::set_allocated_gamma(::mvcam::Parameter* gamma) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete gamma_;
  }
  if (gamma) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      gamma = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, gamma, submessage_arena);
    }
    
  } else {
    
  }
  gamma_ = gamma;
  // @@protoc_insertion_point(field_set_allocated:mvcam.Configuration.gamma)
}

// -------------------------------------------------------------------

// Frame

// .google.protobuf.Timestamp timestamp = 1;
inline bool Frame::has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != NULL;
}
inline const ::google::protobuf::Timestamp& Frame::_internal_timestamp() const {
  return *timestamp_;
}
inline const ::google::protobuf::Timestamp& Frame::timestamp() const {
  const ::google::protobuf::Timestamp* p = timestamp_;
  // @@protoc_insertion_point(field_get:mvcam.Frame.timestamp)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Timestamp*>(
      &::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* Frame::release_timestamp() {
  // @@protoc_insertion_point(field_release:mvcam.Frame.timestamp)
  
  ::google::protobuf::Timestamp* temp = timestamp_;
  timestamp_ = NULL;
  return temp;
}
inline ::google::protobuf::Timestamp* Frame::mutable_timestamp() {
  
  if (timestamp_ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::Timestamp>(GetArenaNoVirtual());
    timestamp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mvcam.Frame.timestamp)
  return timestamp_;
}
inline void Frame::set_allocated_timestamp(::google::protobuf::Timestamp* timestamp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:mvcam.Frame.timestamp)
}

// uint64 id = 2;
inline void Frame::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Frame::id() const {
  // @@protoc_insertion_point(field_get:mvcam.Frame.id)
  return id_;
}
inline void Frame::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:mvcam.Frame.id)
}

// uint32 size = 3;
inline void Frame::clear_size() {
  size_ = 0u;
}
inline ::google::protobuf::uint32 Frame::size() const {
  // @@protoc_insertion_point(field_get:mvcam.Frame.size)
  return size_;
}
inline void Frame::set_size(::google::protobuf::uint32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:mvcam.Frame.size)
}

// uint32 height = 4;
inline void Frame::clear_height() {
  height_ = 0u;
}
inline ::google::protobuf::uint32 Frame::height() const {
  // @@protoc_insertion_point(field_get:mvcam.Frame.height)
  return height_;
}
inline void Frame::set_height(::google::protobuf::uint32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:mvcam.Frame.height)
}

// uint32 width = 5;
inline void Frame::clear_width() {
  width_ = 0u;
}
inline ::google::protobuf::uint32 Frame::width() const {
  // @@protoc_insertion_point(field_get:mvcam.Frame.width)
  return width_;
}
inline void Frame::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:mvcam.Frame.width)
}

// uint32 pixel_format = 6;
inline void Frame::clear_pixel_format() {
  pixel_format_ = 0u;
}
inline ::google::protobuf::uint32 Frame::pixel_format() const {
  // @@protoc_insertion_point(field_get:mvcam.Frame.pixel_format)
  return pixel_format_;
}
inline void Frame::set_pixel_format(::google::protobuf::uint32 value) {
  
  pixel_format_ = value;
  // @@protoc_insertion_point(field_set:mvcam.Frame.pixel_format)
}

// bytes data = 7;
inline void Frame::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Frame::data() const {
  // @@protoc_insertion_point(field_get:mvcam.Frame.data)
  return data_.GetNoArena();
}
inline void Frame::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mvcam.Frame.data)
}
#if LANG_CXX11
inline void Frame::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvcam.Frame.data)
}
#endif
inline void Frame::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvcam.Frame.data)
}
inline void Frame::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvcam.Frame.data)
}
inline ::std::string* Frame::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:mvcam.Frame.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Frame::release_data() {
  // @@protoc_insertion_point(field_release:mvcam.Frame.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Frame::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:mvcam.Frame.data)
}

// -------------------------------------------------------------------

// DeviceInfo

// string manufacture = 2;
inline void DeviceInfo::clear_manufacture() {
  manufacture_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceInfo::manufacture() const {
  // @@protoc_insertion_point(field_get:mvcam.DeviceInfo.manufacture)
  return manufacture_.GetNoArena();
}
inline void DeviceInfo::set_manufacture(const ::std::string& value) {
  
  manufacture_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mvcam.DeviceInfo.manufacture)
}
#if LANG_CXX11
inline void DeviceInfo::set_manufacture(::std::string&& value) {
  
  manufacture_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvcam.DeviceInfo.manufacture)
}
#endif
inline void DeviceInfo::set_manufacture(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  manufacture_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvcam.DeviceInfo.manufacture)
}
inline void DeviceInfo::set_manufacture(const char* value, size_t size) {
  
  manufacture_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvcam.DeviceInfo.manufacture)
}
inline ::std::string* DeviceInfo::mutable_manufacture() {
  
  // @@protoc_insertion_point(field_mutable:mvcam.DeviceInfo.manufacture)
  return manufacture_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceInfo::release_manufacture() {
  // @@protoc_insertion_point(field_release:mvcam.DeviceInfo.manufacture)
  
  return manufacture_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceInfo::set_allocated_manufacture(::std::string* manufacture) {
  if (manufacture != NULL) {
    
  } else {
    
  }
  manufacture_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), manufacture);
  // @@protoc_insertion_point(field_set_allocated:mvcam.DeviceInfo.manufacture)
}

// string id = 3;
inline void DeviceInfo::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceInfo::id() const {
  // @@protoc_insertion_point(field_get:mvcam.DeviceInfo.id)
  return id_.GetNoArena();
}
inline void DeviceInfo::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mvcam.DeviceInfo.id)
}
#if LANG_CXX11
inline void DeviceInfo::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvcam.DeviceInfo.id)
}
#endif
inline void DeviceInfo::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvcam.DeviceInfo.id)
}
inline void DeviceInfo::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvcam.DeviceInfo.id)
}
inline ::std::string* DeviceInfo::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:mvcam.DeviceInfo.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceInfo::release_id() {
  // @@protoc_insertion_point(field_release:mvcam.DeviceInfo.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceInfo::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:mvcam.DeviceInfo.id)
}

// string model = 4;
inline void DeviceInfo::clear_model() {
  model_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceInfo::model() const {
  // @@protoc_insertion_point(field_get:mvcam.DeviceInfo.model)
  return model_.GetNoArena();
}
inline void DeviceInfo::set_model(const ::std::string& value) {
  
  model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mvcam.DeviceInfo.model)
}
#if LANG_CXX11
inline void DeviceInfo::set_model(::std::string&& value) {
  
  model_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvcam.DeviceInfo.model)
}
#endif
inline void DeviceInfo::set_model(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvcam.DeviceInfo.model)
}
inline void DeviceInfo::set_model(const char* value, size_t size) {
  
  model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvcam.DeviceInfo.model)
}
inline ::std::string* DeviceInfo::mutable_model() {
  
  // @@protoc_insertion_point(field_mutable:mvcam.DeviceInfo.model)
  return model_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceInfo::release_model() {
  // @@protoc_insertion_point(field_release:mvcam.DeviceInfo.model)
  
  return model_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceInfo::set_allocated_model(::std::string* model) {
  if (model != NULL) {
    
  } else {
    
  }
  model_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model);
  // @@protoc_insertion_point(field_set_allocated:mvcam.DeviceInfo.model)
}

// string version = 5;
inline void DeviceInfo::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceInfo::version() const {
  // @@protoc_insertion_point(field_get:mvcam.DeviceInfo.version)
  return version_.GetNoArena();
}
inline void DeviceInfo::set_version(const ::std::string& value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mvcam.DeviceInfo.version)
}
#if LANG_CXX11
inline void DeviceInfo::set_version(::std::string&& value) {
  
  version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvcam.DeviceInfo.version)
}
#endif
inline void DeviceInfo::set_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvcam.DeviceInfo.version)
}
inline void DeviceInfo::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvcam.DeviceInfo.version)
}
inline ::std::string* DeviceInfo::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:mvcam.DeviceInfo.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceInfo::release_version() {
  // @@protoc_insertion_point(field_release:mvcam.DeviceInfo.version)
  
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceInfo::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:mvcam.DeviceInfo.version)
}

// string serial = 6;
inline void DeviceInfo::clear_serial() {
  serial_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceInfo::serial() const {
  // @@protoc_insertion_point(field_get:mvcam.DeviceInfo.serial)
  return serial_.GetNoArena();
}
inline void DeviceInfo::set_serial(const ::std::string& value) {
  
  serial_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mvcam.DeviceInfo.serial)
}
#if LANG_CXX11
inline void DeviceInfo::set_serial(::std::string&& value) {
  
  serial_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvcam.DeviceInfo.serial)
}
#endif
inline void DeviceInfo::set_serial(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  serial_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvcam.DeviceInfo.serial)
}
inline void DeviceInfo::set_serial(const char* value, size_t size) {
  
  serial_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvcam.DeviceInfo.serial)
}
inline ::std::string* DeviceInfo::mutable_serial() {
  
  // @@protoc_insertion_point(field_mutable:mvcam.DeviceInfo.serial)
  return serial_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceInfo::release_serial() {
  // @@protoc_insertion_point(field_release:mvcam.DeviceInfo.serial)
  
  return serial_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceInfo::set_allocated_serial(::std::string* serial) {
  if (serial != NULL) {
    
  } else {
    
  }
  serial_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), serial);
  // @@protoc_insertion_point(field_set_allocated:mvcam.DeviceInfo.serial)
}

// -------------------------------------------------------------------

// Status

// double temperature = 1;
inline void Status::clear_temperature() {
  temperature_ = 0;
}
inline double Status::temperature() const {
  // @@protoc_insertion_point(field_get:mvcam.Status.temperature)
  return temperature_;
}
inline void Status::set_temperature(double value) {
  
  temperature_ = value;
  // @@protoc_insertion_point(field_set:mvcam.Status.temperature)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mvcam

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::mvcam::DeviceControlAction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mvcam::DeviceControlAction>() {
  return ::mvcam::DeviceControlAction_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_camera_5fdefinitions_2eproto
