// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera_service.proto

#include "camera_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace CameraServer {
}  // namespace CameraServer
namespace protobuf_camera_5fservice_2eproto {
void InitDefaults() {
}

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "camera_service.proto", schemas, file_default_instances, TableStruct::offsets,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024camera_service.proto\022\014CameraServer\032\033go"
      "ogle/protobuf/empty.proto\032\030camera_defini"
      "tions.proto2\374\006\n\rCameraService\022Y\n\024GetAvai"
      "lableAdapters\022\026.google.protobuf.Empty\032\'."
      "CameraServer.AvailableAdaptersResponse\"\000"
      "\022N\n\nGetDevices\022\034.CameraServer.AdapterReq"
      "uest\032 .CameraServer.DeviceListResponse\"\000"
      "\022F\n\017QueryDeviceById\022\027.CameraServer.IdReq"
      "uest\032\030.CameraServer.DeviceInfo\"\000\022\?\n\nOpen"
      "Camera\022\027.CameraServer.IdRequest\032\026.google"
      ".protobuf.Empty\"\000\022C\n\016ShutdownCamera\022\027.Ca"
      "meraServer.IdRequest\032\026.google.protobuf.E"
      "mpty\"\000\022K\n\017ConfigureCamera\022\036.CameraServer"
      ".ConfigureRequest\032\026.google.protobuf.Empt"
      "y\"\000\022J\n\020GetConfiguration\022\027.CameraServer.I"
      "dRequest\032\033.CameraServer.Configuration\"\000\022"
      "<\n\tGetStatus\022\027.CameraServer.IdRequest\032\024."
      "CameraServer.Status\"\000\0229\n\007Capture\022\027.Camer"
      "aServer.IdRequest\032\023.CameraServer.Frame\"\000"
      "\022J\n\tStreaming\022\036.CameraServer.StreamingRe"
      "quest\032\031.CameraServer.FrameStream\"\0000\001\022@\n\013"
      "ResetDevice\022\027.CameraServer.IdRequest\032\026.g"
      "oogle.protobuf.Empty\"\000\022R\n\022ControlDeviceS"
      "tate\022\".CameraServer.DeviceControlRequest"
      "\032\026.google.protobuf.Empty\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 994);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "camera_service.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fempty_2eproto::AddDescriptors();
  ::protobuf_camera_5fdefinitions_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_camera_5fservice_2eproto
namespace CameraServer {

// @@protoc_insertion_point(namespace_scope)
}  // namespace CameraServer
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
